apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: link-tree-clone-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"  # Adjust if your issuer name is different
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - linktree.ja-zum-leben.at
    secretName: link-tree-clone-tls
  rules:
  - host: linktree.ja-zum-leben.at
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: link-tree-clone-service
            port:
              number: 80