apiVersion: v1
kind: Service
metadata:
  name: link-tree-clone-service
spec:
  selector:
    app: link-tree-clone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP  # Or LoadBalancer if external access needed